# FLEET CONFIG =================================================================
# RMF Fleet parameters
---
rmf_fleet:
  name: "kachaka"
  limits:
    linear: [0.3, 0.75]  # velocity, acceleration
    angular: [0.6, 2.0]  # velocity, acceleration
  profile:  # Robot profile is modelled as a circle
    footprint: 0.3  # radius in m
    vicinity: 0.5  # radius in m
  reversible: false  # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0  # V
    capacity: 24.0  # Ahr
    charging_current: 5.0  # A
  mechanical_system:
    mass: 10.0  # kg
    moment_of_inertia: 5.0  # kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0  # W
  tool_system:
    power: 0.0  # W
  recharge_threshold: 0.10  # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0  # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0  # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: true
  task_capabilities:  # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: true
    delivery: false 
  actions: ["some_action"]
  finishing_request: "charge"  # [park, charge, nothing]
  responsive_wait: true  # Should responsive wait be on/off for the whole fleet by default? false if not specified.
  robots:
    kachaka_0:
      charger: "charge_station"
      # yamllint disable-line rule:line-length
      responsive_wait: false  # Should responsive wait be on/off for this specific robot? Overrides the fleet-wide setting.
      # No mention of responsive_wait means the fleet-wide setting will be used

  robot_state_update_frequency: 10.0  # Hz

fleet_manager:

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

# Optional
reference_coordinates:
